from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('request/', views.request_document, name='request'),
    path('request/payment/<str:order_id>/', views.simulated_payment, name='simulated_payment'),
    path('request/success/<str:order_id>/', views.request_success, name='request_success'),
    path('my-requests/', views.my_requests, name='my_requests'),
    path('request/detail/<str:order_id>/', views.request_detail, name='request_detail'),
    path('request/cancel/<str:order_id>/', views.cancel_request, name='cancel_request'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('profile/', views.user_profile, name='user_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/requests/', views.admin_requests, name='admin_requests'),
    path('dashboard/users/', views.admin_users, name='admin_users'),
    path('dashboard/request/<str:order_id>/', views.admin_request_detail, name='admin_request_detail'),
    path('dashboard/user/verify/<int:profile_id>/', views.admin_verify_user, name='admin_verify_user'),
    path('dashboard/request/delete/<str:order_id>/', views.admin_delete_request, name='admin_delete_request'),
    path('dashboard/messages/', views.admin_contact_messages, name='admin_contact_messages'),
    path('dashboard/message/<int:message_id>/', views.admin_contact_message_detail, name='admin_contact_message_detail'),
    path('dashboard/message/delete/<int:message_id>/', views.admin_delete_contact_message, name='admin_delete_contact_message'),
    path('admin-edit-user/<int:profile_id>/', views.admin_edit_user, name='admin_edit_user'),
    path('admin-delete-user/<int:profile_id>/', views.admin_delete_user, name='admin_delete_user'),
    path('dashboard/payments/', views.admin_payments, name='admin_payments'),
    path('dashboard/payment/<int:transaction_id>/', views.admin_payment_detail, name='admin_payment_detail'),
    path('dashboard/payment/refund/<str:order_id>/', views.admin_issue_refund, name='admin_issue_refund'),
    path('dashboard/payment/approve-refund/<int:transaction_id>/', views.admin_approve_refund, name='admin_approve_refund'),
    path('dashboard/payment/reports/', views.admin_payment_reports, name='admin_payment_reports'),
]