# Generated by Django 5.2.7 on 2025-10-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount in your currency (e.g., PHP or USD).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed')], default='unpaid', help_text='Status of payment.', max_length=20),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID for tracking.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('transcript', 'Academic Transcript'), ('diploma', 'Diploma/Certificate'), ('grade_report', 'Grade Report'), ('enrollment_cert', 'Certificate of Enrollment'), ('good_moral', 'Certificate of Good Moral Character'), ('transfer_cert', 'Transfer Certificate'), ('other', 'Other')], max_length=50),
        ),
    ]
