# Generated by Django 5.2.7 on 2025-10-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docrequest', '0002_documentrequest_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='course',
            field=models.CharField(blank=True, help_text='Your course or program (e.g., BS Computer Science).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Expected or actual graduation year.', null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='school_id',
            field=models.CharField(blank=True, help_text='Your school ID number.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='school_year',
            field=models.CharField(blank=True, help_text='Academic year (e.g., 2023-2024).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='section',
            field=models.CharField(blank=True, help_text='Your class section (e.g., A, B, or 1-A).', max_length=100, null=True),
        ),
    ]
