# Generated by Django 5.2.7 on 2025-10-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docrequest', '0003_documentrequest_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='picked_up',
            field=models.BooleanField(default=False, help_text='Mark when user has picked up the document'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='picked_up_date',
            field=models.DateTimeField(blank=True, help_text='Date when document was picked up', null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pickup_location',
            field=models.CharField(blank=True, help_text="Where to pick up the document (e.g., Registrar's Office, Building A Room 101)", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='ready_for_pickup',
            field=models.BooleanField(default=False, help_text='Mark when document is ready for physical pickup'),
        ),
    ]
