# Generated by Django 5.2.7 on 2025-10-19 17:12

import docrequest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docrequest', '0004_documentrequest_picked_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='attachment',
            field=models.ImageField(blank=True, help_text='Upload an image to help us understand your issue', null=True, upload_to=docrequest.models.contact_attachment_upload_path),
        ),
    ]
