# Generated by Django 5.2.7 on 2025-10-20 02:06

from django.db import migrations, models
import uuid
from datetime import datetime

def generate_order_ids_for_existing_records(apps, schema_editor):
    """Generate unique Order IDs for all existing DocumentRequest records"""
    DocumentRequest = apps.get_model('docrequest', 'DocumentRequest')
    
    for doc_request in DocumentRequest.objects.all():
        # Generate Order ID format: DOC-YYYYMMDD-XXXX
        date_part = datetime.now().strftime('%Y%m%d')
        unique_part = str(uuid.uuid4().hex[:4]).upper()
        order_id = f"DOC-{date_part}-{unique_part}"
        
        # Ensure uniqueness
        attempts = 0
        while DocumentRequest.objects.filter(order_id=order_id).exists() and attempts < 100:
            unique_part = str(uuid.uuid4().hex[:4]).upper()
            order_id = f"DOC-{date_part}-{unique_part}"
            attempts += 1
        
        doc_request.order_id = order_id
        doc_request.save(update_fields=['order_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('docrequest', '0005_remove_documentrequest_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document Request', 'verbose_name_plural': 'Document Requests'},
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='order_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='Unique order identifier (e.g., DOC-20250109-A3F2)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date when payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (GCash/Maya)'), ('cash', 'Cash on Pickup')], default='online', help_text='Choose: Online (Simulated GCash/Maya) or Cash on Pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Simulated payment reference number', max_length=100, null=True),
        ),
        migrations.RunPython(
            generate_order_ids_for_existing_records,
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='order_id',
            field=models.CharField(
                blank=True,
                editable=False,
                help_text='Unique order identifier (e.g., DOC-20250109-A3F2)',
                max_length=20,
                unique=True
        ),
    ),
        migrations.AlterField(
            model_name='documentrequest',
            name='course',
            field=models.CharField(blank=True, help_text='Your course or program (e.g., BS Computer Science)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Expected or actual graduation year', null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or special instructions', null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount in PHP', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed')], default='unpaid', help_text='Payment status (simulated)', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='picked_up',
            field=models.BooleanField(default=False, help_text='Check when user has picked up the document'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='purpose',
            field=models.TextField(help_text='Reason for requesting this document'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='ready_for_pickup',
            field=models.BooleanField(default=False, help_text='Check when document is ready for physical pickup'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='school_id',
            field=models.CharField(blank=True, help_text='Your school ID number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='school_year',
            field=models.CharField(blank=True, help_text='Academic year (e.g., 2023-2024)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='section',
            field=models.CharField(blank=True, help_text='Your class section (e.g., A, B, or 1-A)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
