# Generated by Django 5.2.7 on 2025-10-26 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docrequest', '0006_alter_contactmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='order_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='Unique order identifier (e.g., DOC-20250109-A3F2)', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(help_text='8-digit School ID (e.g., 20230574)', max_length=8, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('faculty', 'Faculty')], default='student', help_text='User role: Student, Alumni, or Faculty', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or College (e.g., College of Engineering)', max_length=100, null=True)),
                ('course', models.CharField(blank=True, help_text='Course/Program (e.g., BS Computer Science)', max_length=100, null=True)),
                ('year_level', models.CharField(blank=True, help_text='Year level (for students: 1st, 2nd, 3rd, 4th)', max_length=20, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Year of graduation (for alumni)', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text="Whether the user's identity has been verified by admin")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['school_id'],
            },
        ),
    ]
