# Generated by Django 5.2.7 on 2025-11-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docrequest', '0008_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='unpaid', help_text='Payment status (simulated)', max_length=20),
        ),
    ]
